name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify --file pom.xml -P ci


  Release:
    name: Release
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [BuildAndTest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          GPG_TTY: "$(tty)" 
        with:
          release-branch-name: "master"
          
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}
          
          maven-repo-server-id: github
          maven-repo-server-username: ${{ secrets.CI_USER }}
          maven-repo-server-password: ${{ secrets.CI_PACKAGES_TOKEN }}

          git-release-bot-name:  ${{ secrets.CI_USER }}
          git-release-bot-email: "admin@codeshield.de"

          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          maven-args: "-DskipTests -P ci"
